FROM python:3.13

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir --upgrade pip
RUN pip install -r requirements.txt

CMD ["celery", "-A", "app.core.celery_worker", "worker", "--loglevel=info"]
