services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_monitor_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=sqlite:///./service_monitoring.db
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: service_monitor_worker
    depends_on:
      - redis
      - api
    environment:
      - DATABASE_URL=sqlite:///./service_monitoring.db
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis
    container_name: service_monitor_redis
    ports:
      - "6379:6379"
